{"detail":"HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v2/models/ocr-model/infer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9e287dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"}